[package]
name = "filecoin-f3-certs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {  workspace = true }
ahash = { workspace = true }
filecoin-f3-gpbft = { path = "../gpbft" }
keccak-hash = { workspace = true }
fvm_ipld_encoding = {workspace = true}

[dev-dependencies]
filecoin-f3-gpbft = { path = "../gpbft", features = ["test-utils"] }
