[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "CC0-1.0",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
  "CDLA-Permissive-2.0",
  "ISC",
  "BSD-3-Clause",
]
exceptions = []

[bans]
multiple-versions = "allow"
