[package]
name = "filecoin-f3-gpbft"
version = "0.1.0"

authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
fvm_ipld_bitfield = "0.6.0"
anyhow = "1.0.86"

