[package]
name = "filecoin-f3-gpbft"
version = "0.1.0"

authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ahash = { workspace = true }
anyhow = "1.0.86"
base32 = "0.5.1"
fvm_ipld_bitfield = "0.6.0"
keccak-hash = "0.10.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
