# Keys and default values are documented here:
# https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
# These should all have either:
# - tracking issues with the "security" label
# - reasons why they're ignored
ignore = [
  "RUSTSEC-2024-0370", # proc-macro-error is unmaintained, depended upon by `fvm_ipld_bitfield`
]

[output]
deny = ["unmaintained"]
format = "terminal"
quiet = false
