[package]
name = "filecoin-f3-blssig"
version = "0.1.0"

authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bls-signatures.workspace = true
bls12_381.workspace = true
thiserror.workspace = true
keccak-hash.workspace = true
serde.workspace = true
filecoin-f3-gpbft = { path = "../gpbft" }

[dev-dependencies]
rand.workspace = true
sha2.workspace = true
hex.workspace = true
